### ISSUE TITLE
NexT v8 Docs

### ISSUE THREAD

**Issue by stevenjoezhang** [next-theme/theme-next-docs#2]
## Previous Roadmap

https://github.com/theme-next/theme-next.org/issues/36
https://github.com/theme-next/theme-next.org/issues/88

---

- [x] Added custom language support feature [#253](https://github.com/theme-next/hexo-theme-next/pull/253) doc?
- [ ] Assets in `docs/theme-settings/` ?
- [x] Rename NexT Configuration to NexT Quick Start in getting-started? (44699d043018944e18008b4c9033d24af50acfeb)
- [x] Add menu.sitemap doc in `docs/getting-started/` (44699d043018944e18008b4c9033d24af50acfeb)
- [x] Move Configuring Menu Items to theme-settings? (c3b965228cbd6b284caf4e7e7db7a8014998961f)
- [x] Docs for `header: false` in Front-matter (1f14e94038b195a16cec9466b24ead0197d94893)
- [x] Docs: alternative to kramed https://www.npmjs.com/package/hexo-renderer-kramed
  Since kramed itself is no longer maintained, using [hexo-renderer-pandoc](https://www.npmjs.com/package/hexo-renderer-pandoc) or hexo-renderer-marked instead would be a good choice. theme-next.org has been updated: https://github.com/theme-next/theme-next.org/commit/520c38d300f234f99928f2b7a445a208f7ab24de
- [x] Multilingual documentation (`language_switcher`) https://github.com/theme-next/hexo-theme-next/pull/1430#issuecomment-605856142, df0fe089936e70b5141a3a0bc236fab3e8383fe4
- [x] Docs for pandoc installation
- [x] Docs for server-side rendering plugins
- [x] Image resolution (tomorrow preview SVG, https://github.com/next-theme/theme-next-docs/commit/8abad20d8e2199900901bea0ae0d40c9b642326e)
- [x] Pin dependencies in package.json (from npm, b607ee6883d5e14cc683bc775b42df7008728c66, 50401c45820179311c3731af66ddc459c4d0c221)
- [x] Docs: rename the post meta text of comment count (https://github.com/theme-next/hexo-theme-next/pull/998#issuecomment-605606753, 8abad20d8e2199900901bea0ae0d40c9b642326e)
- [x] Docs: custom icon image (https://github.com/theme-next/hexo-theme-next/issues/1461, 342e332b309627d0e151e8d06ae54448fffe3363)
- [x] Docs: default page for sub-menu (https://github.com/next-theme/hexo-theme-next/issues/60, ea561e025e58d268b539e6479014bbf72d91223f)
- [ ] Docs: install theme as git submodule
